version: "3.9"
services:
  nginx:
    container_name: nginx
    build:
      context: .
      dockerfile: docker/nginx.Dockerfile
    ports:
      - "80:80"
      - "443:443"
    configs:
      - source: nginx
        target: /etc/nginx/conf.d/default.conf
    restart: on-failure
    depends_on:
      backend:
        condition: service_healthy

  indexer:
    container_name: indexer
    build:
      context: .
      dockerfile: docker/project.Dockerfile
      target: indexer
    environment:
      - APP_ENV=production
    configs:
      - source: indexer
        target: /app/config/production.toml
    restart: on-failure
    depends_on:
      backend:
        condition: service_healthy

  backend:
    container_name: backend
    build:
      context: .
      dockerfile: docker/project.Dockerfile
      target: backend
    ports:
      - "8001:8000"
    environment:
      - APP_ENV=production
    configs:
      - source: backend
        target: /app/config/production.toml
    depends_on:
      migrator:
        condition: service_completed_successfully
    restart: on-failure
    healthcheck:
      test: [ "CMD", "curl", "-f", "http://localhost:8000/healthcheck" ]
      interval: 10s
      timeout: 5s
      start_period: 10s

  migrator:
    container_name: migrator
    build:
      context: .
      dockerfile: docker/project.Dockerfile
    depends_on:
      db:
        condition: service_healthy

  db:
    container_name: db
    image: postgres:15.1
    ports:
      - "5433:5432"
    environment:
      POSTGRES_DB: "indexer_db"
      POSTGRES_USER: "postgres"
      POSTGRES_PASSWORD: "password"
      PGDATA: "/var/lib/postgresql/data/pgdata"
    volumes:
      - ./postgres_data:/var/lib/postgresql/data
    restart: on-failure
    healthcheck:
      test: [ "CMD", "pg_isready", "-U", "postgres" ]
      interval: 10s
      timeout: 5s
      start_period: 10s

  ipfs:
    container_name: ipfs
    image: ipfs/kubo:v0.18.1
    ports:
      - "127.0.0.1:5001:5001"
      - "127.0.0.1:5002:5002"
      - "127.0.0.1:8080:8080"
      - "4001:4001"
    restart: on-failure
#    healthcheck:
#      test: [ "CMD", "pg_isready", "-U", "postgres" ]
#      interval: 10s
#      timeout: 5s
#      start_period: 10s


configs:
  backend:
    file: config/backend_production.toml
  indexer:
    file: config/indexer_production.toml
  nginx:
    file: config/nginx.local.conf

networks:
  monnet:
    attachable: true